# Задача:
*создать ноутбук, в котором будут приведены собственные примеры на языке Python для каждого из представленных свойств матричных вычислений*

<font size="4"> 1. Дважды транспонированная матрица равна исходной матрице 

In [23]:
import numpy as np

A = np.matrix('0 1 2 3; 4 7 12 4; 8 2 10 11')
print(A)
print("\nТранспонированная:\n", A.T)
R = (A.T).T
print("\nТранспонированная второй раз:\n", R)

[[ 0  1  2  3  5]
 [ 4  7 12  4  6]
 [ 8  2 10 11 12]]

Транспонированная:
 [[ 0  4  8]
 [ 1  7  2]
 [ 2 12 10]
 [ 3  4 11]
 [ 5  6 12]]

Транспонированная второй раз:
 [[ 0  1  2  3  5]
 [ 4  7 12  4  6]
 [ 8  2 10 11 12]]


<font size="4"> 2. Транспонирование суммы матриц равно сумме транспонированных матриц

In [99]:
A = np.matrix('11 4; 7 2; 1 3')
B = np.matrix('1 9; 1 5; 2 7')
print(f'A:\n{A},\n\n B:\n {B}')

C = (A + B).T
print("\nТранспонирование суммы матриц:\n", C)

D = A.T + B.T
print("\nСумма транспонированных матриц:\n", D)

A:
[[11  4]
 [ 7  2]
 [ 1  3]],

 B:
 [[1 9]
 [1 5]
 [2 7]]

Транспонирование суммы матриц:
 [[12  8  3]
 [13  7 10]]

Сумма транспонированных матриц:
 [[12  8  3]
 [13  7 10]]


<font size="4"> 3. Транспонирование произведения матриц равно произведению транспонированных матриц раставленных в обратном порядке

In [100]:
A = np.matrix('3 1; 5 6; 3 1')
B = np.matrix('7 3 2; 1 12 11')
print(f'A:\n{A},\n\n B:\n {B}')

C = (A.dot(B)).T
print("\nТранспонирование произведения матриц:\n", C)

D = (B.T).dot(A.T)
print("\nПроизведение транспонированных матриц:\n", D)

A:
[[3 1]
 [5 6]
 [3 1]],

 B:
 [[ 7  3  2]
 [ 1 12 11]]

Транспонирование произведения матриц:
 [[22 41 22]
 [21 87 21]
 [17 76 17]]

Произведение транспонированных матриц:
 [[22 41 22]
 [21 87 21]
 [17 76 17]]


<font size="4"> 4.Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу

In [101]:
k = 5
print(f'A:\n{A},\n\n k:\n {k}')

N =  (k * A).T
print("\nТранспонирование произведения матрицы на число:\n", N)


D =  k * (A.T)
print("\nПроизведение числа на транспонированную матрицу:\n", D)

A:
[[3 1]
 [5 6]
 [3 1]],

 k:
 5

Транспонирование произведения матрицы на число:
 [[15 25 15]
 [ 5 30  5]]

Произведение числа на транспонированную матрицу:
 [[15 25 15]
 [ 5 30  5]]


<font size="4"> 5.Определители исходной и транспонированной матрицы совпадают: 

In [102]:
A = np.matrix('11 3 5; 0 3 1; 13 5 6')
print(f'A:\n{A}')

A_det = np.linalg.det(A)
print(f"\nОпределитель исходной матрицы: {format(A_det, '.9g')}")

A_T_det = np.linalg.det(A.T)
print(f"\nОпределитель транспонированной матрицы матрицы: {format(A_T_det, '.9g')}")

A:
[[11  3  5]
 [ 0  3  1]
 [13  5  6]]

Определитель исходной матрицы: -13

Определитель транспонированной матрицы матрицы: -13


<font size="5"> Действия над матрицами

<font size="3"> Умножение матрицы на число

<font size="4">  1. Произведение единицы и любой заданной матрицы равно заданной матрице: 

In [103]:
A = np.matrix('3 1; 2 6')
print(f"A:\n{A}")

N = 1 * A
print("\nПроизведение единицы и матрицы:\n", N)

A:
[[3 1]
 [2 6]]

Произведение единицы и матрицы:
 [[3 1]
 [2 6]]


<font size="4">  2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [104]:
Zero = np.matrix('0 0 0; 0 0 0; 0 0 0')
P = 0 * A
print(f"Нулевая матрица:\n{Zero}")
print(f"\nПроизведение матрицы на 0:\n{P}")

Нулевая матрица:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Произведение матрицы на 0:
[[0 0]
 [0 0]]


<font size="4">  3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [105]:
A = np.matrix('13 2 6; 7 5 1')

print(f"A:\n{A}")
N = (8 + 1) * A

print(f"\nПроизведение матрицы на сумму чисел:\n{N}")
D = 8 * A + 1 * A
print(f"\nПроизведений матрицы на каждое из этих чисел:\n{D}")

A:
[[13  2  6]
 [ 7  5  1]]

Произведение матрицы на сумму чисел:
[[117  18  54]
 [ 63  45   9]]

Произведений матрицы на каждое из этих чисел:
[[117  18  54]
 [ 63  45   9]]


<font size="4">  4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [106]:
A = np.matrix('8 1 5; 7 7 1; 0 9 18')

print(f"A:\n{A}")
N = (5 * 3) * A
print(f"\nПроизведение матрицы на произведение чисел:\n{N}")

D = 5 * (3 * A)
print(f"\nПроизведений второго числа и заданной матрицы, умноженному на первое число:\n {D}")

A:
[[ 8  1  5]
 [ 7  7  1]
 [ 0  9 18]]

Произведение матрицы на произведение чисел:
[[120  15  75]
 [105 105  15]
 [  0 135 270]]

Произведений второго числа и заданной матрицы, умноженному на первое число:
 [[120  15  75]
 [105 105  15]
 [  0 135 270]]


<font size="4">  5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [107]:
A = np.matrix('0 9 1; 3 5 2; 7 9 5')
B = np.matrix('10 2 5; 1 4 5; 14 1 6')
k = 5

print(f"A:\n{A},\n\n B:\n{B}")


N = k * (A + B)
print(f"\nПроизведение суммы матриц на число:\n{N}")


D = k * A + k * B
print(f"\nCуммa произведений этих матриц на заданное число:\n{D}")

A:
[[0 9 1]
 [3 5 2]
 [7 9 5]],

 B:
[[10  2  5]
 [ 1  4  5]
 [14  1  6]]

Произведение суммы матриц на число:
[[ 50  55  30]
 [ 20  45  35]
 [105  50  55]]

Cуммa произведений этих матриц на заданное число:
[[ 50  55  30]
 [ 20  45  35]
 [105  50  55]]


<font size="5">  Сложение матриц

<font size="4"> 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [108]:
A = np.matrix('14 3; 7 8; 0 9')
B = np.matrix('1 9; 10 5; 12 7')
print(f"A:\n{A},\n\n B:\n{B}")

N = A + B
print(f"\nA + B:\n {N}")

D = B + A
print(f"\nB + A:\n {D}")

A:
[[14  3]
 [ 7  8]
 [ 0  9]],

 B:
[[ 1  9]
 [10  5]
 [12  7]]

A + B:
 [[15 12]
 [17 13]
 [12 16]]

B + A:
 [[15 12]
 [17 13]
 [12 16]]


<font size="4"> 2.  Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [111]:
A = np.matrix('1 4 5; 9 8 2')
B = np.matrix('3 4 6; 7 1 1')
C = np.matrix('9 1 7; 3 4 3')
print(f"A:\n{A},\n\n B:\n{B},\n\n C:\n{C}")

N = A + (B + C)
print(f"\nA + (B + C):\n {N}")
D = (A + B) + C
print(f"\n(A + B) + C:\n {D}")

A:
[[1 4 5]
 [9 8 2]],

 B:
[[3 4 6]
 [7 1 1]],

 C:
[[9 1 7]
 [3 4 3]]

A + (B + C):
 [[13  9 18]
 [19 13  6]]

(A + B) + C:
 [[13  9 18]
 [19 13  6]]


<font size="4"> 3. Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрицей:

In [112]:
A = np.matrix('8 4 3; 2 1 3; 9 3 1')
print(f"A:\n{A}")
print(f"\n-A:\n{A * (-1)}")

N = A + (-1)*A
print(f"\nСумма:\n {N}")

A:
[[8 4 3]
 [2 1 3]
 [9 3 1]]

-A:
[[-8 -4 -3]
 [-2 -1 -3]
 [-9 -3 -1]]

Сумма:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


<font size="5"> Умножение матриц

<font size="4"> 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [113]:
A = np.matrix('4 3; 6 2')
B = np.matrix('1 7; 8 3')
C = np.matrix('6 1; 3 1')
print(f"A:\n{A},\n\nB:\n{B},\n\nC:\n{C}")

N = A.dot(B.dot(C))
print(f"\nA * (B*C):\n{N}")

D = (A.dot(B)).dot(C)
print(f"\n(A*B) * C:\n{D}")

A:
[[4 3]
 [6 2]],

B:
[[1 7]
 [8 3]],

C:
[[6 1]
 [3 1]]

A * (B*C):
[[279  65]
 [276  70]]

(A*B) * C:
[[279  65]
 [276  70]]


<font size="4"> 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [114]:
A = np.matrix('0 2 1; 9 9 2; 5 6 1')
B = np.matrix('4 7 6; 7 2 1; 2 1 8')
C = np.matrix('9 1 7; 9 9 3; 5 6 1')
print(f"A:\n{A},\n\nB:\n{B},\n\nC:\n{C}")

N = A.dot(B + C)
print(f"\nA * (B+C):\n{N}")

D = A.dot(B) + A.dot(C)
print(f"\nA*B + A*C):\n{D}")

A:
[[0 2 1]
 [9 9 2]
 [5 6 1]],

B:
[[4 7 6]
 [7 2 1]
 [2 1 8]],

C:
[[9 1 7]
 [9 9 3]
 [5 6 1]]

A * (B+C):
[[ 39  29  17]
 [275 185 171]
 [168 113  98]]

A*B + A*C):
[[ 39  29  17]
 [275 185 171]
 [168 113  98]]


<font size="4"> 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:

In [115]:
A = np.matrix('2 9; 8 5')
B = np.matrix('5 8; 1 3')
print(f"A:\n{A},\n\nB:\n{B}")
      

N = A.dot(B)
print(f"\nA * B:\n{N}")

D = B.dot(A)
print(f"\nB * A:\n{D}")

A:
[[2 9]
 [8 5]],

B:
[[5 8]
 [1 3]]

A * B:
[[19 43]
 [45 79]]

B * A:
[[74 85]
 [26 24]]


<font size="4"> 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [118]:
A = np.matrix('1 4 7; 7 9 2; 5 6 1')
J = np.eye(3)
print(f"A:\n{A}")

N = J.dot(A)
print(f"\nE*A:\n{N}")

D = A.dot(J)
print(f"\nA*E:\n{D}")

A:
[[1 4 7]
 [7 9 2]
 [5 6 1]]

E*A:
[[1. 4. 7.]
 [7. 9. 2.]
 [5. 6. 1.]]

A*E:
[[1. 4. 7.]
 [7. 9. 2.]
 [5. 6. 1.]]


<font size="4"> 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [121]:
A = np.matrix('1 2 1; 9 9 2; 5 6 1')
J = np.zeros((3, 3))
print(f"A:\n{A}")

N = J.dot(A)
print(f"\nZ*A:\n{N}")

D = A.dot(J)
print(f"\nA*Z:\n{D}")

A:
[[1 2 1]
 [9 9 2]
 [5 6 1]]

Z*A:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

A*Z:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<font size="5"> Определитель матрицы

<font size="4"> 1. Определитель матрицы остается неизменным при ее транспонировании:

In [123]:
A = np.matrix('6 1 7; 2 6 3; 5 6 1')
print(f"A:\n{A}\n")

det_A = round(np.linalg.det(A), 2)
print(f"|A| = {det_A}\n")
print(f"A(T):\n{A.T}\n")

det_A_t = round(np.linalg.det(A.T), 2)
print(f"|A(T)| = {det_A_t}")

A:
[[6 1 7]
 [2 6 3]
 [5 6 1]]

|A| = -185.0

A(T):
[[6 2 5]
 [1 6 6]
 [7 3 1]]

|A(T)| = -185.0


<font size="4"> 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [125]:
A = np.matrix('5 7 2; 9 0 3; 5 2 1')
print(f"A:\n{A}\n")

det_A = round(np.linalg.det(A), 2)
print(f"|A| = {det_A}\n")

A = np.matrix('0 2 7; 0 5 3; 2 6 1')
print(f"A:\n{A}\n")

det_A = round(np.linalg.det(A), 2)
print(f"|A| = {det_A}\n")

A = np.matrix('9 1 7; 6 6 3; 1 1 1')
print(f"A:\n{A}\n")

det_A = round(np.linalg.det(A), 2)
print(f"|A| = {det_A}\n")

A:
[[5 7 2]
 [9 0 3]
 [5 2 1]]

|A| = 48.0

A:
[[0 2 7]
 [0 5 3]
 [2 6 1]]

|A| = -58.0

A:
[[9 1 7]
 [6 6 3]
 [1 1 1]]

|A| = 24.0



<font size="4"> 3. При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [129]:
A = np.matrix('7 8 7; 5 4 3; 5 6 1')
print(f"A:\n{A}\n")

det_A = round(np.linalg.det(A), 2)
print(f"|A| = {det_A}\n")

B = np.matrix('5 6 5; 5 1 1; 5 6 3')
print(f"B:\n{B}\n")

det_B = round(np.linalg.det(B), 2)
print(f"|B| = {det_B}\n")

A:
[[7 8 7]
 [5 4 3]
 [5 6 1]]

|A| = 52.0

B:
[[5 6 5]
 [5 1 1]
 [5 6 3]]

|B| = 50.0



<font size="4"> 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [130]:
A = np.matrix('4 5 4; 9 5 3; 5 1 1')
print(f"A:\n{A}\n")

det_A = round(np.linalg.det(A), 2)
print(f"|A| = {det_A}\n")

A = np.matrix('9 1 8; 5 3 1; 5 2 1')
print(f"A:\n{A}\n")

det_A = round(np.linalg.det(A), 2)
print(f"|A| = {det_A}\n")

A:
[[4 5 4]
 [9 5 3]
 [5 1 1]]

|A| = -26.0

A:
[[9 1 8]
 [5 3 1]
 [5 2 1]]

|A| = -31.0



<font size="4"> 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [131]:
A = np.matrix('3 1 5; 8 6 3; 5 2 1')
k = 5

print(f"A:\n{A}\n")
det_A = round(np.linalg.det(A), 2)
print(f"|A| = {det_A}")
print(f"|A| * k = {det_A * k}\n")

B = A.copy()
B[2, :] = k * B[2, :]
print(f"B:\n{B}\n")

det_B = round(np.linalg.det(B), 2)
print(f"|B| = {det_B}\n")

A:
[[3 1 5]
 [8 6 3]
 [5 2 1]]

|A| = -63.0
|A| * k = -315.0

B:
[[ 3  1  5]
 [ 8  6  3]
 [25 10  5]]

|B| = -315.0



<font size="4"> 6.  Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

In [134]:
A = np.matrix('-3 -1 2; -9 -2 2; 8 3 1')
B = np.matrix('-6 -1 9; 8 2 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(f'C\n{C}')
print(f'A\n{A}')
print(f'B\n{B}')
print("\n|C|")
print(round(np.linalg.det(C), 3))
print("\n|A| + |B|")
print(round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3))

C
[[-3 -1  2]
 [-1  0  4]
 [ 8  3  1]]
A
[[-3 -1  2]
 [-9 -2  2]
 [ 8  3  1]]
B
[[-6 -1  9]
 [ 8  2  2]
 [ 8  3  1]]

|C|
-3.0

|A| + |B|
65.0


<font size="4"> 7.  Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится:

In [135]:
A = np.matrix('5 5 1; 9 3 3; 6 6 1')
k = 5

B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]

print(f"\nA:\n{A}")
print(f"\nB:\n{B}")

print("\n|A|")
print(round(np.linalg.det(A), 2))

print("\n|B|")
print(round(np.linalg.det(B), 2))


A:
[[5 5 1]
 [9 3 3]
 [6 6 1]]

B:
[[ 5  5  1]
 [34 28  8]
 [ 6  6  1]]

|A|
6.0

|B|
6.0


<font size="4"> 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю

In [136]:
A = np.matrix('5 5 1; 9 3 3; 6 6 1')
k = 5
print(f"\nA:\n{A}")

A[1, :] = A[0, :] + k * A[2, :]
print("\n|A|")
print(round(np.linalg.det(A), 3))


A:
[[5 5 1]
 [9 3 3]
 [6 6 1]]

|A|
-0.0


<font size="4"> 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [137]:
A = np.matrix('5 5 1; 9 3 3; 6 6 1')
k = 5
print(f"\nA:\n{A}")
print(round(np.linalg.det(A), 3))

A[1, :] = k * A[0, :]
print(f"\nnew A:\n{A}")
print(round(np.linalg.det(A), 3))


A:
[[5 5 1]
 [9 3 3]
 [6 6 1]]
6.0

new A:
[[ 5  5  1]
 [25 25  5]
 [ 6  6  1]]
-0.0


<font size="5"> Обратная матрица

<font size="4"> 1. Обратная матрица обратной матрицы есть исходная матрица:

In [139]:
A = np.matrix('1 2; 4 1')
print(f"\nA:\n{A}")

A_inv = np.linalg.inv(A)
print(f"\nA_inv:\n{A_inv}")

A_inv_inv = np.linalg.inv(A_inv)
print(f"\nA_inv_inv:\n{A_inv_inv}")


A:
[[1 2]
 [4 1]]

A_inv:
[[-0.14285714  0.28571429]
 [ 0.57142857 -0.14285714]]

A_inv_inv:
[[1. 2.]
 [4. 1.]]


<font size="4"> 2.  Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [142]:
A = np.matrix('1 2; 4 1')

N = np.linalg.inv(A.T)
print(f"Обратная матрица транспонированной матрицы:\n{N}")

D = (np.linalg.inv(A)).T
print(f"\nТранспонированная матрица от обратной матрицы:\n{D}")

Обратная матрица транспонированной матрицы:
[[-0.14285714  0.57142857]
 [ 0.28571429 -0.14285714]]

Транспонированная матрица от обратной матрицы:
[[-0.14285714  0.57142857]
 [ 0.28571429 -0.14285714]]


<font size="4"> 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [144]:
A = np.matrix('1 2; 4 1')
B = np.matrix('3 8; 8 2')


N = np.linalg.inv(A.dot(B))
print(f"Обратная матрица произведения матриц:\n{N}")

D = np.linalg.inv(B).dot(np.linalg.inv(A))
print(f"\nПроизведение обратных матриц:\n{D}")

Обратная матрица произведения матриц:
[[ 0.08374384 -0.02955665]
 [-0.04926108  0.04679803]]

Произведение обратных матриц:
[[ 0.08374384 -0.02955665]
 [-0.04926108  0.04679803]]
