# Задача:
<font size ="4"> *Создать ноутбук, в котором будут приведены собственные примеры решения систем линейных уравнений матричным методом и методом Крамера.*
    
## Решение матричный методом
<font size ="4">  *решение системы линейных алгебраических уравнений по матричному методу определяется равенством*
    $$ X = {A^{-1}} *B$$


1. Создание и заполнение матрицы

In [4]:
import numpy as np

np.random.seed(0)
slae = np.random.randint(0, 25, size = (4, 5))
slae

array([[12, 15, 21,  0,  3],
       [ 3,  7,  9, 19, 21],
       [18,  4, 23,  6, 24],
       [24, 12,  1,  6,  7]])

$$
\begin{cases}
    12x_{1} + 15x_{2} + 21x_{3} = 3 \\
    3x_{1} + 7x_{2} + 9x_{3} + 19x_{4} = 21 \\
    18x_{1} + 4x_{2} + 23x_{3} + 6x_{4} = 24 \\
    24x_{1} + 12x_{2} + 1x_{3} + 6x_{4} = 7
\end{cases}
$$

<font size ="3"> 1. Осуществим перевод к матричному виду:

In [5]:
slae_a = slae[:, 0:4]
slae_b = slae[:, 4]
x = np.ones((4, 1))

print(f"slae_a\n{slae_a}")
print(f"\nslae_b\n{slae_b}")

slae_a
[[12 15 21  0]
 [ 3  7  9 19]
 [18  4 23  6]
 [24 12  1  6]]

slae_b
[ 3 21 24  7]


<font size="4"> Получаем
$$
\bar{A} =  
 \begin{pmatrix} 
  12 & 15 & 21 & 0 | & 3  \\ 
  3 & 7 & 9 & 19 | & 21 \\ 
  18 & 4 & 23 & 6 | & 24 \\
  24 & 12 & 1 & 6 | & 7 \\
 \end{pmatrix}
 $$



<font size ="4"> Нужно найти определитель |A|
    
    
<font size ="3"> находим его по формуле
$$ A^{-1} = E / A $$

In [9]:
#Нахождение определителя
A_deter = np.linalg.det(slae_a)

if A_deter != 0:
    #Нахождение обратной и присоединенной матриц
    A_inv = np.linalg.inv(slae_a)
    x = A_inv.dot(slae_b)
    print(f"Решение:\n{x}")
else:
    print("Матрица вырожденна")

Решение:
[ 0.46213836 -0.94625293  0.55467303  1.11817359]


# Решение методом Крамера
<font size="4">Метод Крамера предназначен для того, чтобы решать системы линейных алгебраических уравнений (СЛАУ), в которых число неизвестных переменных равняется числу уравнений, а определитель основной матрицы не равен нулю.
    
<font size="3">Создадим и заполним матрицу

In [10]:
np.random.seed(0)
slae = np.random.randint(0, 25, size = (4, 5))
slae

array([[12, 15, 21,  0,  3],
       [ 3,  7,  9, 19, 21],
       [18,  4, 23,  6, 24],
       [24, 12,  1,  6,  7]])

<font size="3">Осуществим перевод к матричному виду

In [17]:
slae_a = slae[:, 0:4]
slae_b = np.ones((4, 1))
x = np.ones((4, 1))

slae_b[0, 0] = slae[0, 4]
slae_b[1, 0] = slae[1, 4]
slae_b[2, 0] = slae[2, 4]
slae_b[3, 0] = slae[3, 4]

print(f"slae_a\n{slae_a}")
print(f"\nslae_b\n{slae_b}")

slae_a
[[12 15 21  0]
 [ 3  7  9 19]
 [18  4 23  6]
 [24 12  1  6]]

slae_b
[[ 3.]
 [21.]
 [24.]
 [ 7.]]


<font size="3">Осуществим нахождение определителя и дополнительных определителей и самого решения по формулам Крамера
    $$ x_{1} = \frac{\bigtriangleup_{1}}{\bigtriangleup};
    x_{2} = \frac{\bigtriangleup_{2}}{\bigtriangleup};
    x_{3} = \frac{\bigtriangleup_{3}}{\bigtriangleup}$$

In [20]:
#Нахождения определителя
A_deter = np.linalg.det(slae_a)

if A_deter != 0:
    #Нахождение дополнительных определителей
    for i in range(4):
        A_extra = slae_a.copy()
        A_extra[:, i] = slae_b[:, 0]
        x[i,0] = round(np.linalg.det(A_extra), 2) / round(np.linalg.det(slae_a), 2)
    print(f"Решения:\n{x}")
    print(x)
else:
    print("Матрица вырожденная")

Решения:
[[ 0.46213836]
 [-0.94625293]
 [ 0.55467303]
 [ 1.11817359]]
[[ 0.46213836]
 [-0.94625293]
 [ 0.55467303]
 [ 1.11817359]]
